### ISSUE TITLE
Migrating from jquery-textcomplete

### ISSUE THREAD

**Issue by xPaw** [yuku-t/textcomplete#106]
Could a simple guide on how to migrate be included? Are there any differences that need to be kept in mind?

**Comment by yuku-t** [comment]
Hi @xPaw, thanks for opening the issue.

When it comes to the strategy parameter, there are few breaking changes. So please try following migration:

```js
const el = document.getElementById('your-textarea');

// jquery-textcomplete
$(el).textcomplete(/* your strategies */);

// textcomplete
const Textcomplete = require('textcomplete/lib/textcomplete');
const Textarea = require('textcomplete/lib/textarea');
const editor = new Textarea(el);
const textcomplete = new Textcomplete(editor);
textcomplete.register(/* your strategies */);
```

If this is not enough for you, please let me know.

Note that, if your strategy calls `callback` multiple times in a single search, the behavior is no longer supported.

**Comment by xPaw** [comment]
For some reason I'm getting some jquery conflicts. Could it be webpack or babel?

> jQuery.Deferred exception: Textarea is not a constructor TypeError: Textarea is not a constructor
> Uncaught TypeError: Textarea is not a constructor

**Comment by yuku-t** [comment]
`"x" is not a constructor` error occurs when you attempt to use an object or a variable as a constructor, but that object or variable is not a constructor. I think that you fail to require the textarea object.

![image](https://user-images.githubusercontent.com/96157/27582276-4adf6444-5b6b-11e7-8a30-96a226bcd816.png)

### Ref

- [TypeError: "x" is not a constructor - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_constructor)

**Comment by glebm** [comment]
Here is a conversion commit from an open-source project: https://github.com/thredded/thredded/pull/596/files#diff-8d63ee9e127afc1c4ddd9d3a1b2f8918

**Comment by lannka** [comment]
@xPaw the error is from Babel.

> Babel assigns default exports to the default property. So if you use require to import ES6 modules, you need to access the default property:
> const Button = require('./Components/Button.js').default;

copied answer from [here](https://stackoverflow.com/questions/36388766/unexpected-uncaught-typeerror-xxx-is-not-a-constructor-errors-with-babel-and)

**Comment by bill-mybiz** [comment]
@lannka A small but important point: This is not related to babel per se, as I use webpack + typescript and I also had to use the `default` property. (Thanks! :+1:) 

I think this is more of just an ES6 aspect? And since more and more code going forward will be ES6, perhaps this would be good info on the main README?

**Comment by mikemorton** [comment]
@yuku-t is there a way to get an instance of the textcomplete from the element it is attached to?  Something along the lines of `$('#myelement').data('textcompete')`

**Comment by yuku-t** [comment]
@mikemorton No there isn't. Please use the `Textcomplete` instance you created in the initialization process.
