### ISSUE TITLE
Angular 2 and textcomplete

### ISSUE THREAD

**Issue by blidblid** [yuku-t/textcomplete#112]
I'm trying to use textcomplete in my Angular app, but I can't get it to work. 

```
    import Textcomplete from 'textcomplete/lib/textcomplete';
    import Textarea from 'textcomplete/lib/textcomplete';

    const editor = new Textarea(document.getElementById('textarea'));
    const textcomplete = new Textcomplete(editor);
    textcomplete.register([{}];
```
I'm getting a TypeError in textcomplete.js:217: this.editor.on is not a function. Any idea what's causing that?

Textcomplete looks great and I'd really like to use in my app.

**Comment by yuku-t** [comment]
@blidblid  😎

```diff
     import Textcomplete from 'textcomplete/lib/textcomplete';
-    import Textarea from 'textcomplete/lib/textcomplete';
+    import Textarea from 'textcomplete/lib/textarea';
```

**Comment by blidblid** [comment]
Wow, do I feel silly. 

It works flawlessly now. Great work with this, thanks!

**Comment by PritamPashte** [comment]
Hi, I want to use this library for angular 4 application. i have installed this package but when i import it does not work. i am importing in the following way.
import { TextComplete , Textarea } from 'textcomplete'
![image](https://user-images.githubusercontent.com/24470888/43031942-a61d47aa-8cc9-11e8-8673-78a46809f69c.png)

i am getting the above error. please help

**Comment by Rekhajikki** [comment]
Hi I had tried to use text complete in angular 2. Even I face the same issues as above .
 Try `npm install @types/textcomplete/lib/textarea` if it exists or add a new declaration (.d.ts) file containing `declare module 'textcomplete/lib/textarea';`
Can any help outhow to use it in angular2.

Thanks,
RekhaJikki
