### ISSUE TITLE
How use textcomplete for div element (and HTMLEditable)

### ISSUE THREAD

**Issue by davaxi** [yuku-t/textcomplete#116]
Hi,

In your previous (and deprecated) plugin jquery, you can pass adapter for HTMLContentEditable and display HTML Content. In this library,  how can I do the same thing?

Thanks

**Comment by yuku-t** [comment]
@davaxi ContentEditable has not been supported yet, and probably I don't have time to support it since I'm no longer using ContentEditable.

**Comment by mvlabat** [comment]
That's sad to hear. :(
jquery-textcomplete is the only library, I have found, supporting autocomplete for contenteditable on such level. Have to stick with the deprecated version then...

**Comment by yuku-t** [comment]
@davaxi @mvlabat I've released [textcomplete.contenteditable](https://github.com/yuku-t/textcomplete.contenteditable) (witout tests 😨). Please use it.

Note that it is disabled in Safari due to its `document.execCommand`'s strange behavior. So if Safari support is important, you should keep using the jquery version.

**Comment by yuku-t** [comment]
I'm going to close this issue. If you find any problem, please open an issue to [yuku-t/textcomplete.contenteditable](https://github.com/yuku-t/textcomplete.contenteditable) repo.

**Comment by tnaveen246** [comment]
can any one tell me how to use jquery-textcomplete for TinyMCE editor to supporting autocomplete for contenteditable.

**Comment by andreibondarev** [comment]
I'm curious if anyone has been able to get `textcomplete`/`textcomplete.contenteditable` working with https://github.com/basecamp/trix
