### ISSUE TITLE
replace function breaks down when value is numeric

### ISSUE THREAD

**Issue by mikemorton** [yuku-t/textcomplete#120]
```.ts
    textcomplete.register([{
        match: /(^|\s)(\w+)$/,
        search: (term: string, callback: (res: string[]) => void) => {
                callback(['0000001']); // simplified for example
        },
        replace: (value: string) => {
            return '$1' + value;
        }
    }]);
```

In this case the replace function returns '$10000001' which causes issues in search_result.js because of the custom logic at line 44.

**Comment by yuku-t** [comment]
Thanks for opening the issue. I'd like to tackle this issue this weekend.
 
📝 One way is allowing replace function to return array of arrays of strings. In this case:

```js
replace: value => [['$1', value]]
```

**Comment by mikemorton** [comment]
I'm curious what the logic at line 44 of search_result.js is meant to do?  Is this just duplicating the functionality of string.replace() ?

**Comment by yuku-t** [comment]
> line 44 of search_result.js is meant to do? Is this just duplicating the functionality of string.replace() ?

You mean the following lines?

https://github.com/yuku-t/textcomplete/blob/380643df5db66811f67a4e46f3e575bc9a314c5d/src/search_result.js#L31-L33

**Comment by mikemorton** [comment]
Yes.  But maybe I'm misunderstanding what that code is trying to do 😄

**Comment by mikemorton** [comment]
I changed line 44 from this:
```
replacement = replacement.replace(/\$&/g, match[0]).replace(/\$(\d+)/g, function (_, p1) {
```
to this:
```
replacement = replacement.replace(/\$&/g, match[0]).replace(/\$(\d)/g, function (_, p1) {
```

And it works fine.  (the key is removing the + on the digit matcher, so that it only matches on one digit.  Would you like a PR for this?

**Comment by mikemorton** [comment]
@yuku-t would you accept a PR along the lines of what I describe in my previous post?
