### ISSUE TITLE
Cursor position is not reset correctly when replace returns an array

### ISSUE THREAD

**Issue by mikemorton** [yuku-t/textcomplete#121]
To work around a problem i had with  #120  I changed my code to return an array from the replace function:
```.ts
    textcomplete.register([{
        match: /(^|\s)(\w+)$/,
        search: (term: string, callback: (res: string[]) => void) => {
                callback(['0000001']); // simplified for example
        },
        replace: (value: string) => {
            return ['$1', value];
        }
    }]);
```

With this code I get an issue with the following steps:
1. Start typing 000 - the control autocompletes to 0000001
2. Click on the suggested 0000001

Result: The cursor jumps to before the 0
Desired result: The cursor jumps to after the 1 so the user can continue inputting text.

**Comment by yuku-t** [comment]
This is expected behavior.

> Desired result: The cursor jumps to after the 1 so the user can continue inputting text.

To do so, you have to <code>return `$1${value}`</code> from replace function.
