### ISSUE TITLE
Content Editable Div

### ISSUE THREAD

**Issue by slatkin** [yuku-t/textcomplete#122]
Is it possible or would you know the steps necessary to extend this to a simple contenteditable div (contenteditable="true")>? 

This would be useful to allow HTML markup to highlight autocompleted text, since the textarea can't support it.

**Comment by slatkin** [comment]
I am sorry, I found your repository for that; I should have looked. Thank you so much!

**Comment by yuku-t** [comment]
Yep, you can use https://github.com/yuku-t/textcomplete.contenteditable
