### ISSUE TITLE
2 issues. TypeError: this.el.addEventListener is not a function and dropdown won't close

### ISSUE THREAD

**Issue by neuropass** [yuku-t/textcomplete#134]
Hi,

I switched from the jQuey version to the JS and Im facing two issues:

1)  querySelectorAll does not seem to be working.
the following:

```
var textcomplete = new Textcomplete(
		new Textcomplete.editors.Textarea(document.querySelectorAll('textarea[name="message"], textarea[name="signature"], #myid, .mycustomclass')),
		{
			....
		}
	);
```

will result in error:
https://gyazo.com/675119ab2f8a7ab43e24354febe08d0a

2)
-The drodown will not close.

 if you click outside the dropdown
(was working on the old one: https://yuku-t.com/jquery-textcomplete/ )

the dropdown is not destroyed... 

any thoughts above these two issues?

**Comment by yuku-t** [comment]
1. `Textarea`'s first argument must be an element, not array of element.
2. It is intended change. Please write an event handler to close dropdown.

**Comment by neuropass** [comment]
Hi Yuku-t thanks for your reply. 

Ok, I see but on your jQuery version I used to do this:

`$('textarea[name="message"], textarea[name="signature"], #customID, .myclassi, #AnotherID').textcomplete([`


and would work on any selector present in the page..
How can I achieve the same if querySelectorAll does not work?

**Comment by yuku-t** [comment]
[`document.querySelectorAll()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) returns a [`NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList), so you need to construct textcomplete object for each node.

```js
var nodeList = document.querySelectorAll(/* your selector */)
for (var i = 0, l = nodeList.length; i < l; i++) {
  var node = nodeList[i]
  new Textcomplete(new Textarea(node), { /* your strategies */ })
}
```
