### ISSUE TITLE
No relevant info provided on how to use this plugin with simple jQuery. 

### ISSUE THREAD

**Issue by prakharcipher** [yuku-t/textcomplete#136]
I have been trying to use this plugin for my chrome extension. I am having a hard time figuring out to incorporate it using just jQuery and core Javascript as chrome extension setup doesn't support node or npm. Any help will be highly solicited.

Thanks!

**Comment by yuku-t** [comment]
Please download textcomplete-x.x.x.tgz from [release page](https://github.com/yuku-t/textcomplete/releases) and unarchive it. Then you can find dist/textcomplete.min.js, so put the file in your chrome extension project.

**Comment by prakharcipher** [comment]
@yuku-t Thanks. That solved the issue.
