### ISSUE TITLE
Invalid dropdown menu positioning for textarea when line-height is not set

### ISSUE THREAD

**Issue by michauzo** [yuku-t/textcomplete#143]
This is what happens when the line-height is not set in textarea:
![image](https://user-images.githubusercontent.com/2987177/37962571-d3b0e6c2-31bb-11e8-8d6a-b9b08feaf695.png)

**Comment by michauzo** [comment]
In such case the line-height is calculated by taking height of the cloned editor. By default textarea has 2 rows. This means that the calculated line-height is 2 times bigger than it should be. A fix for this issue is proposed in pull-request #144

**Comment by yuku-t** [comment]
I couldn't reproduce the issue. What browser are you using?

![image](https://user-images.githubusercontent.com/96157/38070835-ee77554c-3358-11e8-8560-9d205fafa0f0.png)

**Comment by michauzo** [comment]
I checked this on Chrome and Edge. Actually I checked this out as you did and I got the same result - so it's not a matter of the browser. However, if you set line-height to unset the computed value is still in pixels, because it could be derived from other styles. But if you set it to normal, then the computed value is also normal and the issue can be reproduced.
