### ISSUE TITLE
Incorrect line height computation

### ISSUE THREAD

**Issue by JoshyPHP** [yuku-t/textcomplete#88]
I'm having some problems with the dropdown's positioning in textareas where `line-height` is set in CSS and the dropdown would appear much lower than expected. I tracked it down to the textarea's line height computation. It seems that those two branches are switched up:
https://github.com/yuku-t/textcomplete/blob/48ae47b08684668a83813b104c207c9b128e5988/src/utils.js#L116-L122

In this code, if the computed line height ends with a digit, it is returned as-is. If it ends with a letter (presumably the `x` from `px`) it's multiplied by computed font size. As per the comment, it should be the other way around: if the computed value is unit-less, multiply it by the font size, otherwise it means it's already in pixels.

Tagging @glebm so he can confirm whether it checks out.

**Comment by glebm** [comment]
@JoshyPHP I'll send a fix shortly, sorry and thanks for tracking this down!

**Comment by yuku-t** [comment]
@JoshyPHP Thanks for reporting the issue. I've released v0.9.1 with the fix.
